/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HomeLab__factory } from "./HomeLab__factory";
export { Material__factory } from "./Material__factory";
