export const MARBLES = [
	"Metropolis Marble",
	"Urbanite Marble",
	"Metro Marble",
	"Cityscape Marble",
	"Skyscraper Marble",
	"Contemporary Marble",
	"Cosmopolitan Marble",
	"Futuristic Marble",
	"Dynamic Marble",
	"Highline Marble",
	"Heritage Marble",
	"Legacy Marble",
	"Tradition Marble",
	"Iconic Marble",
	"Ancestral Marble",
	"Antique Marble",
	"Classic Marble",
	"Historical Marble",
	"Cultural Marble",
	"Authentic Marble",
	"Pure Marble",
	"Simple Marble",
	"Clean Marble",
	"Minimal Marble",
	"Essential Marble",
	"Zen Marble",
	"Sleek Marble",
	"Streamlined Marble",
	"Basic Marble",
	"Understated Marble",
	"Forge Marble",
	"Rustic Marble",
	"Raw Marble",
	"Metal Marble",
	"Steel Marble",
	"Iron Marble",
	"Factory Marble",
	"Industrial Marble",
	"Machined Marble",
	"Workshop Marble",
	"Nexus Marble",
	"Quantum Marble",
	"Cosmos Marble",
	"Horizon Marble",
	"Infinity Marble",
	"Space Age Marble",
	"High-Tech Marble",
	"Digital Marble",
	"Neo Marble",
	"Futuristic Marble",
	"Vintage Marble",
	"Classic Marble",
	"Nostalgia Marble",
	"Antique Marble",
	"Old-fashioned Marble",
	"Retro Marble",
	"Timeless Marble",
	"Traditional Marble",
	"Vintage-inspired Marble",
	"Mid-century Marble",
	"Glamour Marble",
	"Gatsby Marble",
	"Artisan Marble",
	"Deco Marble",
	"Chic Marble",
	"Elegance Marble",
	"Luxury Marble",
	"Art Deco-inspired Marble",
	"Elite Marble",
	"Jazz Age Marble",
	"Pop Marble",
	"Colorful Marble",
	"Funky Marble",
	"Vibrant Marble",
	"Playful Marble",
	"Groovy Marble",
	"Whimsical Marble",
	"Bold Marble",
	"Pop Art-inspired Marble",
	"Graphic Marble",
	"Eames Marble",
	"Atomic Marble",
	"Nelson Marble",
	"Retro Marble",
	"MCM Marble",
	"Danish Marble",
	"Sputnik Marble",
	"Mid-century Marble",
	"Atomic Age Marble",
	"Mad Men Marble",
	"Boho Marble",
	"Natural Marble",
	"Eclectic Marble",
	"Bohemian Marble",
	"Organic Marble",
	"Artisanal Marble",
	"Rustic Marble",
	"Handmade Marble",
	"Tribal Marble",
	"Vintage-inspired Marble",
	"Hygge Marble",
	"Nordic Marble",
	"Minimalist Marble",
	"Scandinavian Marble",
	"Simple Marble",
	"White Marble",
	"Nordic-inspired Marble",
	"Light Marble",
	"Snow Marble",
	"Arctic Marble",
	"Zenith Marble",
	"Elite Marble",
	"Fusion Marble",
	"Contemporary Marble",
	"Modern Marble",
	"Sleek Marble",
	"High-end Marble",
	"High-design Marble",
	"Contemporary-inspired Marble",
	"Designer Marble",
];

export const LIGHT_AND_DARKS_STYLES = [
	"Soft light",
	"Gentle light",
	"Ethereal light",
	"Radiant light",
	"Sunlight",
	"Golden light",
	"Warm light",
	"Ambient light",
	"Glowing light",
	"Fresh light",
	"Pure light",
	"Crisp light",
	"Clean light",
	"Airy light",
	"Bright light",
	"Illuminated light",
	"Luminous light",
	"Naturalistic light",
	"Daylight",
	"Effulgent light",
	"Darkened",
	"Shadowy",
	"Dim",
	"Gloomy",
	"Mysterious",
	"Noir",
	"Gothic",
	"Macabre",
	"Eerie",
	"Sinister",
	"Moody",
	"Brooding",
	"Ominous",
	"Melancholy",
	"Somber",
	"Blackened",
	"Murky",
	"Twilight",
	"Dusky",
	"Obscure",
];
